
		<!-- Footer -->
			<footer id="footer">
				<div class="container">
				<ul class="icons">

				<li><a href="https://pliss2017.github.io">PLISS 2017</a></li>
				<li><a href="https://pliss2019.github.io">PLISS 2019</a></li>
				<li><a href="https://pliss.org/2020">PLISS 2020</a></li>
				<li><a href="https://pliss.org/2021">PLISS 2021</a></li>
				<li><a href="https://pliss.org/2022">PLISS 2022</a></li>
				<li><a href="https://pliss.org/2023">PLISS 2023</a></li>
				<li><a href="https://pliss.org/2025">PLISS 2025</a></li>
                    </ul>
					<ul class="copyright">
						<li>&copy; 2025 PLISS</li>
						<li>Design: <a href="http://templated.co">TEMPLATED</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="../2020/assets/js/jquery.min.js"></script>
			<script src="../2020/assets/js/skel.min.js"></script>
			<script src="../2020/assets/js/util.js"></script>
			<script src="../2020/assets/js/main.js"></script>

	</body>
</html>
