
		<!-- Footer -->
			<footer id="footer">
				<div class="container">
					<ul class="icons">
						<li><a href="https://pliss2019.github.io/">PLISS 2019</a></li>
						<li><a href="https://pliss.org/2020">PLISS 2020</a></li>
                    </ul>
					<ul class="copyright">
						<li>&copy; 2021 PLISS</li>
						<li>Design: <a href="http://templated.co">TEMPLATED</a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>
